---
- name: Pull and Run docker image of schnshrma01/spe-calculator
  hosts: all
  tasks:
    - name: Pull schnshrma01/spe-calculator
      docker_image:
        name:schnshrma01/spe-calculator
        source: pull